sudo: false
language: node_js
node_js: 8
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
script:
- npm run test
after_success:
- npx semantic-release
deploy:
  provider: heroku
  api_key:
    secure: SRiHeUsFL5oh69+Vw6lN1TlxB0eQWWIl0XzhLd0oOTUM1NxuU9Mq9PXalNNt69b+g6cwrb2JkMjkh1MhsgkC3T2QhU4ax/H9buDDsG2ab+vLX7H2ZXtppU3xzqAFG+y/Tw++TbrGrEGsiXoYIb3GC7l1nthxw3bhbgQ7HP48M9sVaflm/wSsARvigrqVuSdbg1u1SQLFuEc8RRSXYTL92A8gAqKRIeBZRBoYYuJO0gIeNV6pjCyCtFIAgrJpPRRD5RKeJOfw4U6C4bVzW1U17mslqSbNFPhGDXN0qOf/zr5SMQ8fJyl9AGuE+JT767QkFLDXdKoR0rNVOO1cySlihBGGBw7rZSVSBLrpDtS9ta1Kf+7GvsJMwYeppfGQJcLzO47nR7Owz6vwoB9GZ8Jr/DVru+r8CS+DehLpWEGV76DmkVL8hI3y4bcM1p0/bQOXrmr+0i7wRy0WmGLf2MRUiQY59HvfOaKArrXqwCQl+rNdPIfqBZ3H0+WDKcel5WJkWt6cZaGr04v9IcrjN0CC0YW89QSzUZJx/apyNyslnp2iT71WIyPsZwxMu5MBeq4sjqAaL5gUJzDxooQmynG71bAz51IMmoXMUhRfWk2+I9zbA1h0tg61/PejX2DFZuNaUtFGVHnpoojZA5LNr8ryNef6IHk374ZYC6ELgicpSiE=
  app: rick-morty-characters
  on:
    repo: guilhermespopolin/rick-morty-characters-sanctuary
